output = """
0bb1011110101011011011111011101111
0bb011110101011011011111011101111
0bb11110101011011011111011101111
0bb1110101011011011111011101111
0bb110101011011011111011101111
0bb10101011011011111011101111
0bb0101011011011111011101111
0bb101011011011111011101111
0bb01011011011111011101111
0bb1011011011111011101111
0bb011011011111011101111
0bb11011011111011101111
0bb1011011111011101111
0bb011011111011101111
0bb11011111011101111
0bb1011111011101111
0bb011111011101111
0bb11111011101111
0bb1111011101111
0bb111011101111
0bb11011101111
0bb1011101111
0bb011101111
0bb11101111
0bb1101111
0bb101111
0bb01111
0bb1111
0bb111
0bb11
0bb1
0bb
"""
